#!/bin/bash
# Check to see if a pipe exists on stdin.
# https://stackoverflow.com/questions/19408649/pipe-input-into-a-script

VERSION=1.0.1
AUTHOR=mqfellow@mqfellow.io
printenv
CURDIR=`pwd`

if [ -p /dev/stdin ]; then
        echo "Data was piped to this script!"
        # If we want to read the input line by line
        touch out.arm
        while IFS= read line; do
                #echo "Line: ${line}"
                echo ${line} >> out.arm
        done
        # Or if we want to simply grab all the data, we can simply use cat instead
        # cat
        ls -al out.arm
        cat out.arm
        
        #begin certrec logic
        pwd && ls -al
        mkdir -p mftmp/mq-certs/$MF_CERTREQ_PREFIX/$MF_CERTREQ_LABEL
        aws s3 sync s3://$MF_CERTREQ_S3_BUCKET/mq-certs/$MF_CERTREQ_PREFIX/$MF_CERTREQ_LABEL ./mftmp/mq-certs/$MF_CERTREQ_PREFIX/$MF_CERTREQ_LABEL
        mv out.arm mftmp/mq-certs/$MF_CERTREQ_PREFIX/$MF_CERTREQ_LABEL/$MF_CERTREQ_LABEL.arm
        cd ./mftmp/mq-certs/$MF_CERTREQ_PREFIX/$MF_CERTREQ_LABEL
        pwd && ls -al
        cat $MF_CERTREQ_LABEL.csr
        runmqakm -cert -add -db key.kdb -label "COMODO RSA Domain Validation Secure Server CA" -file /mf/cli/cert/comodo/bundle1.txt -stashed
        runmqakm -cert -add -db key.kdb -label "COMODO RSA Certification Authority" -file /mf/cli/cert/comodo/bundle2.txt -stashed
        runmqakm -cert -add -db key.kdb -label "AddTrust External CA Root" -file /mf/cli/cert/comodo/bundle3.txt -stashed
        runmqakm -cert -receive -db key.kdb -file $MF_CERTREQ_LABEL.arm -stashed -format ascii 
        runmqakm -cert -list -db key.kdb -stashed
        pwd && ls -al

        # upload to s3
        cd $CURDIR
        aws s3 sync ./mftmp/mq-certs/$MF_CERTREQ_PREFIX/$MF_CERTREQ_LABEL s3://$MF_CERTREQ_S3_BUCKET/mq-certs/$MF_CERTREQ_PREFIX/$MF_CERTREQ_LABEL

        echo 'Done.'

else
        echo "No input was found on stdin, skipping!"
        # Checking to ensure a filename was specified and that it exists
        if [ -f "$1" ]; then
                echo "Filename specified: ${1}"
                echo "Doing things now.."
        else
                echo "No input given!"
        fi
fi

